#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-AU-ACN
version:      0.28
version_from: lib/Business/AU/ACN.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
